# settings optimized for development in a Vagrant VM
base_url: url
admin_password: password
secret_key: key
db_uri: postgresql://postgres/gavel
disable_email: false
email_from: 'Mtest@mail.com' # needs to be set to something even though email is disabled
email_password: ''
email_host: 'smtp'
email_port: 1025