version: '2'
services:
  postgres:    
    build: database/.    
    volumes: 
     - /data/database:/var/lib/postgresql/data
    restart: always
    environment: 
     - POSTGRES_DB:gavel  
  smtp:
    image: mailhog/mailhog:latest
    #build: smtp/.   
  voting:
    container_name: voting
    build: voting/.  
    ports: 
     - "80:5000"    
    restart: always
    depends_on:
     - postgres
     - smtp
    links: 
      - postgres:postgres
      - smtp:smtp
    command: bash -c "python initialize.py && /usr/local/bin/gunicorn -w 2 -b :5000 gavel:app"

